### PR TITLE
Port to Mbed TLS

### PR DESCRIPTION
**Pull request by mskvortsov**
OpenSSL has been deprecated since IDF 4.4 and is no longer available in IDF 5.

### CODE REVIEW

**Comment by mskvortsov** [comment]
This change allows us to proceed with https://github.com/meshtastic/firmware/pull/3960.

**Comment by mverch67** [comment]
mbed has declared EOL:

https://forums.mbed.com/t/important-update-on-mbed-end-of-life/23644

**Comment by fifieldt** [comment]
Read and agree with the move. ESP-TLS also uses mbed TLS internally.

**Review by fifieldt — APPROVED** [review]

**Comment by fifieldt** [comment]
@thebentern @caveman99 - tagging you since this repo might not appear on your regular review queue

**Review by thebentern — APPROVED** [review]

**Comment by caveman99** [comment]
LGTM. Comes in handy for ESP32-C6 support too.

**Review by caveman99 — APPROVED** [review]

**Pull request merged**
